apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    release: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      release: prod
  template:
    metadata:
      labels:
        app: auth
        release: prod
        version: v1.0
    spec:
      containers:
      - name: auth
        image: ccr.ccs.tencentyun.com/carcar/auth:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          exec:
            command: ["/bin/grpc-health-probe", "-addr=:8081"]
          initialDelaySeconds: 5
      imagePullSecrets:
        - name: qcloudregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
  type: ClusterIP