apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob
  labels:
    app: blob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob
  template:
    metadata:
      labels:
        app: blob
        version: v1.0
    spec:
      containers:
      - name: blob
        image: ccr.ccs.tencentyun.com/carcar/blob:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
        - name: qcloudregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: blob
spec:
  selector:
    app: blob
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
  type: ClusterIP