apiVersion: v1
kind: Secret
metadata:
  name: cos
type: Opaque
stringData:
  url: https://coolcar-1307768051.cos.ap-guangzhou.myqcloud.com
  secid: AKIDYw4vWqtfAPq1wue8LJ0PXOzJM8eutb4G
  seckey: xd2B3ey0lFSQ7YibFciX5NO8cplQoxua